protobom/protobom

- go.mod
- go.sum
- pkg/sbom/document.go
- pkg/sbom/document_test.go
- pkg/sbom/edge.go
- pkg/sbom/node.go
- pkg/sbom/node_test.go
- pkg/sbom/nodelist.go
- pkg/sbom/nodelist_test.go
This PR adds the first batch of API functions around the objects autogenerated from the proto.
All of these functions are not yet in use in the current reader/writer flows we are developing. The goal of this API is to make it easier to work with these objects from applications that use `protobom` as a library. In other words, this PR should not affect the translation logic we are building, it only supercharges the autogenerated objects to make them easier to use.
I wrote simple tests for most functions, I will add more test cases as the API moves forward.
The initial API functions include:
| Object | Method | Description |
| --- | --- | --- |
| Edge | Copy() | Deep copies an Edge object |
| Edge | PointsTo() | Returns a bool if an edge points to an element  |
| Node | Copy() | Deep copies …
> Initial Elements API Check-in

- .github/workflows/go-build-and-test.yml
Fix #15
Add testing in GitHub Actions CI. It both builds and tests `protobom`. Test coverage is low. But that can be fixed in other PRs.
> Add testing in CI

- pkg/sbom/edge.go
- pkg/sbom/node.go
- pkg/sbom/nodelist.go
- pkg/sbom/nodelist_test.go
This PR adds an `Equal()` method to the `Edge`, `Node` and `NodeList` objects that lets users of the protobom API compare two objects to each other to find out if their data is the same:
```go
if node1.Equal(node2) {
fmt.Println("Nodes are the same!")
}
```
It does so by adding an internal `flatString()` method to the objects that serializes their data into a comparable string.
As a drive-by, I've rewritten the the `sbom.TestNodeListIntersect` to use the new method from the nodelist effectively deflaking it.
> Add Equals Methods, deflake sbom.TestNodeListIntersect

- .github/workflows/stale.yml
This PR creates a stale issue bot.
More info here: https://github.com/marketplace/actions/close-stale-issues
The default value is that issues and PRs will be marked stale after two months of no activity. Once marked stale, issues and PRs with no further activity will be closed seven days later. (Assuming I understand the documentation correctly.)
> Create stale issue and PR bot

- .golangci.yaml
- cmd/cli/root.go
- internal/writer/options.go
- pkg/formats/formats.go
- pkg/formats/spdx/spdx.go
- pkg/reader/implementation.go
- pkg/reader/unserializer_spdx23.go
- pkg/sbom/document.go
- pkg/sbom/functions.go
- pkg/sbom/nodelist.go
- pkg/sbom/nodelist_test.go
- pkg/writer/implementation.go
- pkg/writer/serializer_cdx.go
- pkg/writer/serializer_spdx23.go
This is a followup to https://github.com/bom-squad/protobom/pull/33 mainly to fix a bug discovered while adding the golangci lint job to the repo and to fix some warning which were valid but were muted.
This PR also adds a config file for golangci-lint enabling a few more linters. I've fixed all the warnings caused by the new linters and I will slowly be cranking up a few more in the coming weeks (see comments in the configuration files).
/cc @jspeed-meyers 
> golangci linter followup

- go.mod
- go.sum
- pkg/formats/sniffer.go
- pkg/formats/spdx/spdx.go
- pkg/sbom/externalreference.go
- pkg/sbom/person.go
- pkg/writer/serializer_spdx23.go
This PR adds a couple of improvements to the SPDX code in protobom:
- Support for external references in the serializer
- Creator, supplier and originator 
- Record of protobom version in the document creation info
> SPDX Improvenments

- pkg/sbom/edge.go
- pkg/sbom/node.go
- pkg/sbom/nodelist.go
- pkg/sbom/nodelist_test.go
This PR introduces two new functions to the protobom API:
- nodelist.RelateNodeListAtID(): his method takes a nodelist n2 and relates its top level elements to
the a node in nodelist nl1 using an edge type.
- nodelist.GetNodesByPurlType : return all methods that match a package URL type.
It also includes a final commit to further deflake some tests that deal with checking the consistency of the graph operations.
> Protobom API Improvements

- pkg/reader/implementation.go
- pkg/reader/unserializer_cdx14.go
- pkg/sbom/hashalgorithm.go
This PR introduces the first iteration of the CycloneDX unserializer.
It supports most protobom fields (still missing are tools and persons) but it creates the correct protobom graph taking into account if the SBOM has a top-level component or not.
Requires the API improvements introduced in #46 (and probably a rebase)
> Add CycloneDX 1.4 unserializer

- pkg/formats/spdx/spdx.go
- pkg/sbom/externalreference.go
- pkg/sbom/identifier.go
- pkg/sbom/identifier_test.go
This PR restores a few methods in the protobom identifier object which either I had forgotten to commit or that I overwrote at some point by mistake.
> Restore identifier SPDX convenience methods

- pkg/reader/unserializer_cdx14.go
- pkg/reader/unserializer_spdx23.go
- pkg/sbom/identifier.go
- pkg/sbom/node.go
- pkg/writer/serializer_cdx.go
- pkg/writer/serializer_spdx23.go
This PR fixes a bug where all serializers and parsers were storing and reading the purl from the `node.ExternalReferences` list. The protobom model has a dedicated collection for software identifiers to keep them apart from the rest of the other references. This makes sure the data is being stored in the right place.
Signed-off-by: Adolfo Garcia Veytia (puerco) <puerco@chainguard.dev>
> Fix purl and CPE retrieval and storage

- pkg/sbom/node.go
- pkg/sbom/nodelist.go
- pkg/sbom/nodelist_test.go
This PR introduces a new method called `GetMatchingNode()` to the `NodeList` object. This method looks for a node that matches the passed node:
```golang
matchingNode, err = nodelist.GetMatchingNode(testnode)
```
A "matching node" is a node that describes the same piece of software as the test node. This function is critical because node IDs are only valid within the document, so when looking for a matching node from a second SBOM, ID-based comparison cannot be done.
The function guarantees only one matching node. If there is ambiguity and two nodes from the nodelist fit the testnode, an error is returned.
The method looks for matching nodes by comparing the hashes first and if no match is done it tries to match based on the purl of the nodes. Purl matching needs a bit more polishing but …
> nodelist.GetMatchingNode()

- docs/development.md
A fundamental development getting-started doc. 
We cannot assume everybody uses VSCode so I made it more general, we can go back to it later.
Once we add `Make` commands we should update this docs as well.
> docs: add devcontainer getting started

- pkg/reader/implementation.go
- pkg/writer/implementation.go
- pkg/writer/serializer_cdx.go
This commit adds a simple plugin interface in the reader and writer packages to load the serializers and unserializers of the native formats.
This new registration metaphor lets applications register alternative implementations of the drivers that read and write the native SBOM formats.
This change maintains compatibility with the previous implementation, no API changes.
Related to https://github.com/bom-squad/protobom/pull/72
> Pluginize the load of serializers and unserializers

- pkg/writer/serializer_cdx.go
This commit adds support for the protobom Metadata.Authors field to be written as CycloneDX Metadata.Authors field.  They are datatype cdx.OrganizationalContact:
```
if bom.Metadata != nil && len(bom.GetMetadata().GetAuthors()) > 0 {
var authors []cdx.OrganizationalContact
for _, bomauthor := range bom.GetMetadata().GetAuthors() {
authors = append(authors, cdx.OrganizationalContact{
Name:  bomauthor.Name,
Email: bomauthor.Email,
Phone: bomauthor.Phone})
}
metadata.Authors = &authors
}
```
> Add writer support for Authors

- hack/README.md
This PR adds a short readme to start documenting scripts in the hack directory
> Add README documenting scripts in ./hack

- pkg/native/serializers/beta/serializer_spdx3.go
This commit adds the beginning of an SPDX 3.0 serializer.
It is not enabled by default, applications wishing to use it need to purposedly include the package and it will auto-register with the protobom writer. Here is a sample program that converts one of the example SBOMs to SPDX3:
```golang
package main
import (
"fmt"
"os"
"github.com/bom-squad/protobom/pkg/formats"
_ "github.com/bom-squad/protobom/pkg/native/serializers/beta"
"github.com/bom-squad/protobom/pkg/reader"
"github.com/bom-squad/protobom/pkg/writer"
)
func main() {
r := reader.New()
bom, err := r.ParseFile("examples/curl.spdx.json")
if err != nil {
fmt.Fprint(os.Stderr, err)
os.Exit(1)
}
w := writer.New()
w.Options.Format = formats.Format("text/spdx+json;version=3.0")
if err := w.WriteStream(bom, os.Stdout); err != nil { …
```
> Alpha SPDX 3.0 Serializer

- pkg/native/serializers/serializer_cdx.go
My last change in this area was actually incorrect.  if protobom node.Type is "file" then CycloneDX Type MUST be "file".  
When ingesting an SBOM, this is what is supposed to happen:
* If we ingest cdx, the component.Type value should go to the primarypurpose field
** Additionally if component.Type is "file" the node should be marked as Node_FILE
* If we ingest spdx goes from primary purpose to primary purpose
When rendering the node to native SBOM:
* If it's SPDX the value goes from primary purpose to primary purpose
* If it's CDX:
** If the node is Node_FILE component.Type is file. Nothing else should happen or the graph will break.
** All others should go from the primary purpose to component.Type
Thanks @puerco for setting me straight here.  We would have had data loss without this …
> ensure c.Type == file if node.Type is file

- pkg/native/serializers/serializer_cdx_test.go
This adds a test to ensure file nodes are rendered as file-typed components in CDX.
Follow up to https://github.com/bom-squad/protobom/pull/95
/cc @veramine 
> CDX Serializer: Add Primary Purpose to Type unit test

- pkg/native/serializers/serializer_cdx.go
Fill in CDX "Supplier" if at least one sbom Suppliers is set.  If more than one is set, we lose them.  I'm open to other ideas here but proposing this as a starting point.  
```
+       if n.Suppliers != nil && len(n.GetSuppliers()) > 0 {
+               // TODO(degradation): CDX type Component only supports one Supplier while protobom supports multiple
+
+               nodesupplier := n.GetSuppliers()[0]
+               oe := cdx.OrganizationalEntity{
+                       Name: nodesupplier.GetName(),
+               }
+               if nodesupplier.Contacts != nil {
+                       var contacts []cdx.OrganizationalContact
+                       for _, nodecontact := range nodesupplier.GetContacts() {
+                               newcontact := cdx.OrganizationalContact{ …
```
> Populate cdx Supplier from node.Suppliers

- pkg/native/serializers/serializer_cdx.go
Fixes an issue found by fuzzing (https://github.com/bom-squad/sbom-convert/pull/13). Added check to return error if serializer root component is nil.
```
rootComponent, err := s.root(ctx, bom)
if err != nil {
return nil, fmt.Errorf("generating SBOM root component: %w", err)
} else if rootComponent == nil {
return nil, fmt.Errorf("No SBOM root component")
}
```
(the else if is added)
> Return error if native serializer does not return valid root node

- pkg/native/unserializers/unserializer_spdx23.go
Fixes an issue found by fuzzing (https://github.com/bom-squad/sbom-convert/pull/13).  Added check for nil CreationInfo before trying to use it. 
```
if spdxDoc.CreationInfo != nil {
...
}
```
> Ignore CreationInfo if not present

- pkg/formats/sniffer.go
- pkg/formats/sniffer_test.go
- pkg/formats/testdata/minified.cdx.json
Attempt to read just the SpecVersion from the JSON via json.Unmarshal.  If this succeeds, use that version.  If it fails, use the string hacks in place already.
Added a test case for the minified json included in the issue.
Fixes https://github.com/bom-squad/protobom/issues/112
> Use json.Unmarshal to get CDX specVersion (replacing string hacks)

- pkg/formats/sniffer.go
I'm proposing to revert the change I made yesterday to fix https://github.com/bom-squad/protobom/issues/112.  This implementation is better as it will capture both the SPDX and CDX versions in one shot without having to do any string hacks. Thanks for suggestion @puerco
> Capture the SPDX version and CDX version both in one shot

- pkg/native/serializers/serializer_cdx.go
- pkg/native/unserializers/unserializer_cdx.go
- pkg/writer/options.go
- pkg/writer/writer.go
- pkg/writer/writer_test.go
This PR completes some of the smaller nits outstanding from #102:
* Fixes a possible panic when casting the document to the native format in the CDX serializer
* Removes the default format when initializing the writer
It also fixes a bug where the serializer test would panic when testing for errors, it assumed a fixed number of executions in the fake tests.
Ahead of the cycle meeting we will cut a new release after this PR merges.
Signed-off-by: Adolfo Garcia Veytia (puerco) <puerco@chainguard.dev>
> Small fixes following up on 102

- README.md
The writer does not specify a default format with the 0.2.0 release (via https://github.com/bom-squad/protobom/pull/115/commits/653cb1b1fd870b2345f50ed68f7c3b6112a5e504).  Change the README code example to specify a writer format explicitly. 
```
//w := writer.New(writer.WithFormat(formats.SPDX23JSON))
w := writer.New(writer.WithFormat(formats.CDXFORMAT))
```
Fixes https://github.com/bom-squad/protobom/issues/116
> Changed README example for protobom 0.2.0 release

- README.md
CycloneDX 1.5 is supported now, right?
> Update Supported Formats and Version Table

- pkg/native/nativefakes/fake_serializer.go
- pkg/native/serializer.go
- pkg/native/serializers/beta/serializer_spdx3.go
- pkg/native/serializers/serializer_cdx.go
- pkg/native/serializers/serializer_spdx23.go
- pkg/writer/options.go
- pkg/writer/writer.go
- pkg/writer/writer_test.go
This PR restructures the options data structures to address the problems delineated in #122. It is a set of changes to improve the usability and consistency of the writer object and its option. The changes are as follows:
* It modifies the writer to have a single options struct that embeds a single instance of the render and serialize options while keeping a catalog to host each of the serializer driver functions.
* The serializer functions now take a set of common options (render and serialize options) and the native serializer options.
* The fakes have been updated accordingly.
* The writer options now have functions to set and get each driver's options set.
* Tests are updated to handle the new universal options struct
The new options struct looks as follows:
```golang
type Options …
```
> Reorganize options data structures

- pkg/native/nativefakes/fake_unserializer.go
- pkg/native/unserializer.go
- pkg/native/unserializers/unserializer_cdx.go
- pkg/native/unserializers/unserializer_spdx23.go
- pkg/reader/options.go
- pkg/reader/reader.go
- pkg/reader/reader_test.go
This PR restructures the reader options just as we did for the writer options in #123. It basically creates a single Options set that embeds the unserializer and a collection for the serializer driver options. It is a big PR but it is mostly harmless as we don't have any options defined yet and the design principles are the same as in #123:
```golang
type Options struct {
Format             formats.Format
UnserializeOptions: *native.UnserializeOptions {}
formatOptions      map[string]interface{}
}
```
Note: This is a blocker for cutting v0.2.0 as it evens out the patterns in the readers and writers.
Signed-off-by: Adolfo Garcia Veytia (puerco) <puerco@chainguard.dev>
> Restructure reader options

- pkg/native/serializers/serializer_cdx.go
With CycloneDX, the root node is expected to be in the node list.  However, in SPDX the Document section can be the root node with no package or file otherwise acting as the root node.  I had previously added a check in the CycloneDX serializer to reject protobom documents where the root node was not in the node list.  (https://github.com/bom-squad/protobom/pull/109)  That change does not allow some protobom documents originating from a valid SPDX document to be written to CycloneDX.  See https://github.com/bom-squad/protobom/issues/126.
Example originating SBOM:  
[in.json](https://github.com/bom-squad/protobom/files/12899027/in.json)
With this change, we allow CDX serialization of protobom Documents where the root node is not in the Node List.  I contemplated instead adding a fake node …
> Allow serialization of SBOM with no rootComponent

- pkg/sbom/node_test.go
PR https://github.com/bom-squad/protobom/pull/133 added deep copy for Node.  This test ensures it works for embedded structures Licenses (slice), Hashes (map), FileTypes (slice), Suppliers (Person) and Originators (Person).
```
func TestNodeCopy(t *testing.T) {
original := &Node{
Licenses: []string{"Apache-2.0"},
Hashes: map[int32]string{
int32(HashAlgorithm_SHA1):   "f3ae11065cafc14e27a1410ae8be28e600bb8336",
int32(HashAlgorithm_SHA256): "4f232eeb99e1663d07f0af1af6ea262bf594934b694228e71fd8f159f9a19f32",
int32(HashAlgorithm_SHA512): "8044d0df34242699ad73bfe99b9ac3d6bbdaa4f8ebce1e23ee5c7f9fe59db8ad7b01fe94e886941793aee802008a35b05a30bc51426db796aa21e5e91b7ed9be",
},
FileTypes: []string{"TEXT"},
Suppliers: []*Person{
{
Name:  "John Doe",
Email: "john@doe.com",
},
},
Originators: []*Person{ …
```
> Added test for node.Copy()

- README.md
- pkg/sbom/edge.go
- pkg/sbom/node.go
- pkg/sbom/node_test.go
- pkg/sbom/nodelist.go
- pkg/sbom/nodelist_test.go
This PR introduces new functions to the protobom graph API. It adds a few new capabilities to make life easier when working with SBOMs and new functionality.
New features:
-  `nodelist.NodeDescendants` is a new function that traverses the graph starting from a node and returns all linked nodes up to a set distance.
- `nodelist.AddRootNode` is the equivalent of `nodelist.AddNode` but it also registers the node as a root node.
- `nodelist.RelateNodeAtId` inserts a node into the graph by relating it to a specified node.
Quality of life improvements:
- `node.AddHash` is a convenience function to add hashes to nodes.
- We now have constructors for the protobom elements (eg `n := NewNode()` )
I've added tests for all new functions and simplified the readme with the new functions.
Signed-off-by: …
> Graph API improvements

- pkg/sbom/diff.go
- pkg/sbom/diff_test.go
This PR is the first of a series to build diffing capabilities into the protobom core. This PR starts with diffing support in the node. To compare two nodes, you simply call the new node.Diff method and pass it a second node to compare:
```golang
diff := node1.Diff(node2)
```
The result is a new simple structure called `NodeDiff` that captures in two nodes data from fields that were changed or added, data that was removed and the number of changes:
```golang
type NodeDiff struct {
Added     *Node
Removed   *Node
DiffCount int
}
```
I've added some tests to the diff function that verify the integration with some of the helper functions, they can be improved and we should probably create a conformance framework to test diffing.
Note: Needs #140 to run
Signed-off-by: Adolfo Garcia Veytia …
> Node diffing!

- CODEOWNERS
wey no longer works for Manifest Cyber, therefore, he is no longer a maintainer≈
> chore: remove wey from maintainers

- go.mod
- go.sum
- pkg/native/serializers/serializer_cdx.go
This PR updates the cycloneDX libraries to v0.8.0. It only fixes the serializer to use the new ToolChoice struct introduced in the latest version. It does not yet support the new component-based tool.
/cc @manifestori @veramine 
Signed-off-by: Adolfo Garcia Veytia (puerco) <puerco@chainguard.dev>
> Bump CDX libraries to 0.8

- pkg/native/unserializers/unserializer_cdx.go
This PR fixes a panic in the external reference code in the cdx unserializer
This unlocks https://github.com/bom-squad/protobom/pull/147
Signed-off-by: Adolfo Garcia Veytia (puerco) <adolfo.garcia@uservers.net>
> Fix CycloneDX ExtRef Panic

- .github/dependabot.yml
- .github/workflows/go-build-and-test.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/release.yaml
- upgrade to use go1.22 
- update dependabot config to add groups and github actions
> upgrade to use go1.22 

- pkg/sbom/edge.go
- pkg/sbom/edge_test.go
- pkg/sbom/nodelist.go
- pkg/sbom/nodelist_test.go
This commit fixes a bug that was causing edges from the source NodeList
to be lost when calling `nodelist.RelateNodeAtID()`.
Signed-off-by: Adolfo García Veytia (Puerco) <puerco@stacklok.com>
> Fix missing relationships in nodelist.RelateNodeAtID()

- pkg/reader/options.go
- pkg/reader/reader.go
- pkg/storage/backend.go
- pkg/storage/filesystem.go
- pkg/writer/options.go
- pkg/writer/writer.go
This PR is a minor update to the recently added `StoreRetriever` interface and the `ProtobomType` type constraint.
- Add separate `Storer` and `Retriever` interfaces that `StoreRetriever` embeds
- This enables backends to create types that only implement one behavior or the other if desired
- `Backend` definition unchanged
- For the struct types that comprise the `ProtobomType` type constraint, change to pointer types (e.g. `sbom.Node` --> `*sbom.Node`), but leave maps as-is
- A map is already a reference, so implementing methods for `*map[sbom.HashAlgorithm]string` and `*map[sbom.SoftwareIdentifierType]string` causes issues with dereferencing
> Backend interface update

- pkg/writer/writer.go
- refactored the code to use sync.Once and sync.Map primitives
> refactor to use sync.Map and sync.Once for writer

- pkg/reader/options.go
- pkg/reader/reader.go
- pkg/storage/backend.go
- pkg/storage/filesystem.go
- pkg/writer/options.go
- pkg/writer/writer.go
In addition to the current protobom types in the type constraint, this PR allows for implementing `Storer` and `Retriever` for **_slices_** of certain of those types. For example:
```go
// Store implements the Storer interface for *sbom.Node.
func (backend *NodeBackend) Store(n *sbom.Node, opts *storage.StoreOptions) error {
//
}
// Retrieve implements the Retriever interface for *sbom.Node.
func (backend *NodeBackend) Retrieve(id string, opts *storage.RetrieveOptions) (*sbom.Node, error) {
//
}
```
as well as
```go
// Store implements the Storer interface for []*sbom.Node.
func (backend *NodesBackend) Store(n []*sbom.Node, opts *storage.StoreOptions) error {
//
}
// Retrieve implements the Retriever interface for []*sbom.Node.
func (backend *NodesBackend) Retrieve(id string, opts …
```
> Revert StoreRetriever to only accept Document

- CODEOWNERS
Following up on our community meeting from May 22nd this PR promotes the new group of commuters to the project:
| GitHub Handle | Promotion Issue |
| --- | --- |
| @jhoward-lm | https://github.com/protobom/community/issues/1  |
| @cpanato  | https://github.com/protobom/community/issues/3 |
| @eddiezane | https://github.com/protobom/community/issues/2 |
/cc @protobom/admins 
Signed-off-by: Adolfo García Veytia (Puerco) <puerco@stacklok.com>
> New protobom commiters 🎉🎉🎉🎉

- README.md
The word definition is spelled as definiton in the first paragraph of the readme file. This commit corrects the spelling.
> fix: Update README.md to correct spelling of definition

- CONTRIBUTING.md
- README.md
Per issue #245, adds a set of community links (slack and WG meetings) to README.md and CONTRIBUTING.md, modeled after similar content in the bomctl project docs.
> Add community links to readme and contributing docs to resolve issue 245

- README.md
- docs/unserializers.md
The `README.md` has broken reference to `docs/parsers.md`. Looking at the code I figured `Unserializer` is what is used by `readers` to read a specific SBOM format into neutral `protobom` object.
> fix: README.md to replace parser with unserializer

- docs/options/README.md
- docs/options/serializers/README.md
- docs/options/serializers/spdx23.md
- pkg/native/serializers/serializer_spdx23.go
- pkg/native/serializers/serializer_spdx23_test.go
This commit modifies the SPDX namespace behavior when serializing documents. This change properly handles the URL fragments when writing the SPDX document, stripping it from the doc when defined. It also ensures that other valid URIs such as urns and package URLs can be piped and used as valid namespaces.
The PR introduces two options into the serializer to ensure that we can control when things go wrong: `FailOnInvalidDocIdFragment` and `GenerateDocumentId`, documentation for the serializer options is included as well as a unit test.
Signed-off-by: Adolfo García Veytia (puerco) <puerco@stacklok.com>
> Formalize SPDX 2.3 namespace behavior

- pkg/mod/mod.go
- pkg/native/serializer.go
- pkg/native/unserializer.go
- pkg/reader/options.go
- pkg/writer/options.go
This PR introduces protobom _mods_. 
A _mod_ is a flag that enables a custom behavior in protobom which breaks the universal document model but is nevertheless implemented as it models a solution to an edge case or a common SBOM practice.
Mods are gated so they are only activated when an application requests them. The protobom mods are activated in the reader and writer and are enabled as properties of the serializer and unserializer options.
This PR adds functional arguments to enable and disable them at construction time. The mod package is checked in but it's empty. The first mod we'll add will be the "cdx properties to SPDX annotations" solution that will soon follow this PR.
> Protobom mods

- pkg/native/serializers/serializer_spdx23.go
Adds section to handle the addition of Author information to CreationInfo.Creators slice.
Tested locally with bomctl e2e test 
Closes #261
> fix: spdx 23 serializer handle Authors

- pkg/mod/mod.go
- pkg/native/serializer.go
- pkg/native/serializers/serializer_spdx23.go
- pkg/native/serializers/serializer_spdx23_test.go
- pkg/native/unserializer.go
Now that support for the protobom mods has merged (ref https://github.com/protobom/protobom/pull/264) this PR introduces the first mod: `SPDX_RENDER_PROPERTIES_IN_ANNOTATIONS`. 
This mod causes the protobom annotations to be rendered as a json struct of the property proto embedded in the SPDX annotations of the resulting package. To enable, initialize a writer with the mod and render the protobom to SPDX 2.3:
```golang
w := writer.New(
writer.WithMod(mod.SPDX_RENDER_PROPERTIES_IN_ANNOTATIONS),
writer.WithFormat(formats.SPDX23JSON),
)
w.WriteStream(doc, os.Stdout)
```
(Note that the code example requires https://github.com/protobom/protobom/pull/275 which fixes a bug that causes the options to panic)
Here's an example SBOM with properties rendered as annotations:
```json
{
"spdxVersion": …
```
> Support properties in annotations through SPDX mod :tada: 

- pkg/reader/options.go
- pkg/writer/options.go
This PR fixes a panic when using the `WithMod` functional option for the first time in the reader and the writer.
> Fix panic in WithMod when initializing

- pkg/datasink/listener.go
- pkg/reader/options.go
- pkg/reader/reader.go
- pkg/writer/options.go
- pkg/writer/writer.go
This PR introduces new data sink capabilities into the protobom library. Specifically, we now define a new `datasink.Listener` class that defines an object that can tap into the SBOM data stream. When registering a Listener with the reader, the listener will get a copy of all the SBOM data as it is read. The analogous also is implemented in the writer: in addition to the main data stream, any registered listeners will also get a copy of the generated SBOM data when writing.
Listeners are super easy to implement,  the interface simply wraps `io.Writer`:
```golang
type Listener interface {
io.Writer
}
``` 
To register a new Listener, you pass anything that implements the interface through the reader and writer options, for example, to output the SBOM data to stderr as it is written to …
> Support for SBOM data sinks

- pkg/mod/mod.go
- pkg/native/unserializers/unserializer_spdx23.go
- pkg/native/unserializers/unserializer_spdx23_test.go
- pkg/reader/reader.go
This PR follows up #276 and adds a new mod `SPDX_READ_ANNOTATIONS_TO_PROPERTIES` which is on by default in the reader. When enabled, the SPDX unserializer will look for annotations in packages done by `protobom - v1.0.0` and if the comment decodes to a valid property, it will register them in the node's properties.
This is the inverse of #276 which added support for the writing mod.
> Support properties/annotations mod when reading

- pkg/reader/reader.go
- pkg/reader/reader_test.go
@jhoward-lm ran into issues using the new hash field in protobom/storage. This updates `setSourceData` to encode the hash as a string. Test values also updated.
> fix: encode source data hash as string

- pkg/native/unserializer.go
- pkg/reader/internal_test.go
- pkg/reader/options.go
- pkg/reader/reader.go
- pkg/reader/reader_test.go
With #278 merged, we can now pipe the I/O of the reader and writer. This PR refactors the document source data reader to avoid a triple sequential read we had in the SBOM stream. I've dropped the original test as now we only need to check the correct assignment of the source data.
This PR also adds the computation of the stream hashes in sha1 (for spdx 2.x references) and sha512 .
We now also have a new `TrackSource` option in the unserializer to enable/disable the tracking of the source doc data. It is enabled by default.
> Refactor source reader

- pkg/native/serializers/serializer_spdx23.go
> fix: assign `PackageOriginator` under `Originators`

- go.mod
As discussed in the feb12 community meeting, [go 1.24 has been released](https://go.dev/blog/go1.24) so we now bump the minimal supported version in the protobom core libraries to 1.23.
/cc @protobom/core-commiters 
Signed-off-by: Adolfo García Veytia (Puerco) <adolfo.garcia@uservers.net>
> Bump minimal go version to 1.23

- pkg/writer/writer.go
This commit modifies the writer to take a plain `io.Writer` instead of an `io.WriterCloser` which does not really need. Probably a legacy from early development.
Note that this change does not break the function signature as the writer interface is 100% compatible.
(the other changed lines are simplifying a double import)
Signed-off-by: Adolfo García Veytia (Puerco) <puerco@carabiner.dev>
> Writer: Use io.Writer instead of WriterCloser

- pkg/native/serializers/serializer_cdx.go
- pkg/native/serializers/serializer_cdx_test.go
This PR rewrites the cyclonedx recursion that generates the components
tree and dependency graph to fix several bugs and lost data.
It simplifies the recursion and does away with the previous implementation
that passed data around in a context.
Signed-off-by: Adolfo Garcia Veytia (puerco) <adolfo.garcia@uservers.net>
> Rewrite cdx recursion

- pkg/native/serializers/serializer_spdx23.go
- pkg/native/serializers/serializer_spdx23_test.go
Current behavior:
`"licenseDeclared": "BSD-2-clauseORBSD-3-clauseORExpat-with-advertising-restrictionORMazieres-BSD-styleOROpenSSHORPowell-BSD-styleORpublic-domain",`
Expected white space between OR to make it a valid SPDX license expression: https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/
> Add whitespace in PackageLicenseDeclared concatenation

- pkg/native/serializers/serializer_spdx23.go
- pkg/native/serializers/serializer_spdx23_test.go
Protobuf output is not deterministic: https://github.com/golang/protobuf/issues/1121
Plus SPDX 2.3 docs mention that timestamps should be in a particular format. 
```
YYYY-MM-DDThh:mm:ssZ
where:
YYYY is year
MM is month with leading zero
DD is day with leading zero
T is delimiter for time
hh is hours with leading zero in 24 hour time
mm is minutes with leading zero
ss is seconds with leading zero
Z is universal time indicator
```
> Use SPDX2.3 timestamp format - `YYYY-MM-DDThh:mm:ssZ` during serialization
